language: elixir
sudo: false
elixir:
  - 1.2.6
  - 1.3.1
otp_release:
  - 18.1
  - 19.0
notifications:
  recipients:
    - jose.valim@plataformatec.com.br
before_install:
  - wget -c https://github.com/jgm/pandoc/releases/download/1.15.0.6/pandoc-1.15.0.6-1-amd64.deb
  - ar -x pandoc-1.15.0.6-1-amd64.deb
  - tar xzf data.tar.gz
  - export PATH=$PATH:$PWD/usr/bin/
  - nvm install 5.3.0
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g npm
  - npm install
env:
  - MIX_ENV=test
script:
  - "mix do local.hex --force, deps.get, test --include pandoc, coveralls.travis"
  - node_modules/.bin/gulp
cache:
  directories:
    - node_modules
    - deps
