language: elixir
sudo: false
elixir: 1.4.1
otp_release: 19.1
matrix:
  include:
    - elixir: 1.3.0
      otp_release: 18.1
notifications:
  recipients:
    - jose.valim@plataformatec.com.br
before_install:
  - nvm install 5.3.0
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g npm
  - npm install
env:
  - MIX_ENV=test
script:
  - mix do local.hex --force
  - mix deps.get
  - mix test
  - mix coveralls.travis
  - node_modules/.bin/gulp
cache:
  directories:
    - node_modules
    - deps
