language: erlang
sudo: false
elixir:
  - 1.0.2
otp_release:
  - 17.4
node_js:
  - "iojs"
notifications:
  recipients:
    - jose.valim@plataformatec.com.br
before_install:
  - wget -c https://github.com/jgm/pandoc/releases/download/1.15.0.6/pandoc-1.15.0.6-1-amd64.deb
  - ar -x pandoc-1.15.0.6-1-amd64.deb
  - tar xzf data.tar.gz
  - export PATH=$PATH:$PWD/usr/bin/
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g npm
  - npm install
script:
  - "mix do local.hex --force, deps.get && mix test --include pandoc"
  - node_modules/.bin/gulp
