language: elixir
sudo: false
before_script:
  - sh -e /etc/init.d/xvfb start
before_install:
  - nvm install $NODE_VERSION
script:
  - if [ "$CHECK_FORMATTED" = true ]; then mix format --check-formatted; fi
  - mix test
  - bash test/prerelease.sh
  - if [ "$CHECK_JS" = true ];  then npm install; npm run lint; npm run test; fi
cache:
  directories:
    - node_modules
    - deps
addons:
  firefox: "54.0"
env:
  global:
    - MIX_ENV=test
    - DISPLAY=:99.0
    - NODE_VERSION="10.10.0"
matrix:
  include:
    - elixir: 1.5.3
      otp_release: 19.3
    - elixir: 1.8.1
      otp_release: 21.2
    - elixir: 1.9.0
      otp_release: 22.0
      env: CHECK_FORMATTED=true
      env: CHECK_JS=true
